### ISSUE TITLE
model.ckpt-10859.data-00000-of-00001; No such file or directory

### ISSUE THREAD

**Issue by amnsr17** [guillaume-chevalier/ReuBERT#31]
When I try to run the system, I get this error.
`model.ckpt-10859.data-00000-of-00001; No such file or directory`
And it is true that I do not have this file included under the directory:
ReuBERT/thales-bert-gcp-bucket/squad_large/
But I do have another file: model.ckpt-10859.index
Is there something I am missing in terms of understanding how this system is supposed to run?

**Comment by guillaume-chevalier** [comment]
You probably missed the instructions here on how to use Google GCP: 
https://github.com/guillaume-chevalier/ReuBERT/tree/master/cloud_scripts
